import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import TrendingSection from "@/components/TrendingSection";
import CategorySection from "@/components/CategorySection";
import HowItWorks from "@/components/HowItWorks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" 
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className=" flex flex-col bg-base-100 text-base-content min-h-screen">
        <Navbar/>
      
        {children}
        <ToastContainer
    position="top-right"
    autoClose={3000}
  />
  <TrendingSection/>
  <CategorySection/>
  <HowItWorks/>
         <Footer/>
        </body>
        
    </html>
  );
}
